### ISSUE TITLE
Connection reset warnings

### ISSUE THREAD

**Issue by martinohanlon** [zhuowei/RaspberryJuice#49]
When a client disconnects, a "connection reset" warning is presented in the log. This isnt required.

```
[21:26:26 WARN]: java.net.SocketException: Connection reset
[21:26:26 WARN]:        at java.net.SocketInputStream.read(Unknown Source)
[21:26:26 WARN]:        at java.net.SocketInputStream.read(Unknown Source)
[21:26:26 WARN]:        at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
[21:26:26 WARN]:        at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
[21:26:26 WARN]:        at sun.nio.cs.StreamDecoder.read(Unknown Source)
[21:26:26 WARN]:        at java.io.InputStreamReader.read(Unknown Source)
[21:26:26 WARN]:        at java.io.BufferedReader.fill(Unknown Source)
[21:26:26 WARN]:        at java.io.BufferedReader.readLine(Unknown Source)
[21:26:26 WARN]:        at java.io.BufferedReader.readLine(Unknown Source)
[21:26:26 WARN]:        at net.zhuoweizhang.raspberryjuice.RemoteSession$InputThread.run(RemoteSession.java:625)
[21:26:26 WARN]:        at java.lang.Thread.run(Unknown Source)
[21:26:26 INFO]: [RaspberryJuice] Closed connection to/127.0.0.1:56935.
```

**Comment by martinohanlon** [comment]
included in v1.9.1
