### ISSUE TITLE
Bug `mc.getPlayerEntityIds()` when no user is connected to the server.

### ISSUE THREAD

**Issue by dglaude** [zhuowei/RaspberryJuice#55]
I believe there is a bug in the command `mc.getPlayerEntityIds()` when no user is connected to the server.

I hope I am using the latest version because I the Mac Kit from here: https://adventuresinminecraft.github.io/

Here is a little piece of code that demonstrate the problem:

```python
# http://eu.wiley.com/WileyCDA/WileyTitle/productCd-111894691X.html
#

# The Minecraft API has to be imported before it can be used
import mcpi.minecraft as minecraft

# To communicate with a running Minecraft game, you need a connection to that game.
mc = minecraft.Minecraft.create()

mc.postToChat("+++ath 1")

# This should get the list of players connected
players= mc.getPlayerEntityIds()

mc.postToChat("+++ath 2")

# Try to display this on the chat
mc.postToChat("players="+str(players))

mc.postToChat("+++ath 3")

# END
```

If I run this code with a single user connected, here is the output:

```
[15:26:07 INFO]: XXXXXXXX[/192.168.192.120:37148] logged in with entity id 14 at ([world]111.10392722469632, 80.20000004768372, 119.8046478129002)
[15:26:33 INFO]: [RaspberryJuice] Starting input thread
[15:26:33 INFO]: [RaspberryJuice] Opened connection to/127.0.0.1:52665.
[15:26:33 INFO]: [RaspberryJuice] Starting output thread!
[15:26:33 INFO]: +++ath 1
[15:26:33 INFO]: +++ath 2
[15:26:33 INFO]: players=[14]
[15:26:33 INFO]: +++ath 3
```

When I run this code without any user connected to the server, here is the error I get:

```
[15:18:11 INFO]: [RaspberryJuice] Opened connection to/127.0.0.1:52624.
[15:18:11 INFO]: [RaspberryJuice] Starting input thread
[15:18:11 INFO]: [RaspberryJuice] Starting output thread!
[15:18:11 INFO]: +++ath 1
[15:18:11 WARN]: [RaspberryJuice] Error occured handling command
[15:18:11 WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[15:18:11 WARN]: 	at java.lang.AbstractStringBuilder.deleteCharAt(AbstractStringBuilder.java:824)
[15:18:11 WARN]: 	at java.lang.StringBuilder.deleteCharAt(StringBuilder.java:253)
[15:18:11 WARN]: 	at net.zhuoweizhang.raspberryjuice.RemoteSession.handleCommand(RemoteSession.java:181)
[15:18:11 WARN]: 	at net.zhuoweizhang.raspberryjuice.RemoteSession.handleLine(RemoteSession.java:133)
[15:18:11 WARN]: 	at net.zhuoweizhang.raspberryjuice.RemoteSession.tick(RemoteSession.java:113)
[15:18:11 WARN]: 	at net.zhuoweizhang.raspberryjuice.RaspberryJuicePlugin$TickHandler.run(RaspberryJuicePlugin.java:167)
[15:18:11 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53)
[15:18:11 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[15:18:11 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:689)
[15:18:11 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:366)
[15:18:11 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:650)
[15:18:11 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:554)
[15:18:11 WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dglaude** [comment]
My experiment are here: https://gist.github.com/dglaude/57b1aaf432360e998464875690ff0158

I also believe that getPlayerId(playerName) does not behave well when the player is not connected to the server.

**Comment by martinohanlon** [comment]
Yes, this would create an error. This should be changed to return an empty string. Need to check to make sure the mcpi python library will return an empty list.

**Comment by martinohanlon** [comment]
On 2nd thoughts, I think this should return Fail to be consistent with the rest of the api.

**Comment by martinohanlon** [comment]
in 1.10.1
