### ISSUE TITLE
unable to start thread listener

### ISSUE THREAD

**Issue by iosdev474** [zhuowei/RaspberryJuice#69]
[02:34:37 WARN]: java.net.BindException: Address already in use (Bind failed)
[02:34:37 WARN]: 	at java.net.PlainSocketImpl.socketBind(Native Method)
[02:34:37 WARN]: 	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
[02:34:37 WARN]: 	at java.net.ServerSocket.bind(ServerSocket.java:375)
[02:34:37 WARN]: 	at java.net.ServerSocket.bind(ServerSocket.java:329)
[02:34:37 WARN]: 	at net.zhuoweizhang.raspberryjuice.ServerListenerThread.<init>(ServerListenerThread.java:21)
[02:34:37 WARN]: 	at net.zhuoweizhang.raspberryjuice.RaspberryJuicePlugin.onEnable(RaspberryJuicePlugin.java:74)
[02:34:37 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[02:34:37 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[02:34:37 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[02:34:37 WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:346)
[02:34:37 WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:318)
[02:34:37 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:403)
[02:34:37 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:368)
[02:34:37 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:323)
[02:34:37 WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:241)
[02:34:37 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506)
[02:34:37 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[02:34:37 WARN]: [RaspberryJuice] Failed to start ThreadListener

i tested on port 4711 and other ports in config.yml

**Comment by iosdev474** [comment]
i can use 1.3 and tried same method on latest version but showing this exception.

**Comment by martinohanlon** [comment]
You are receiving a socket error 'Address already in use (Bind failed)'

Do you have more than once instance running?

Is something blocking creating ports?

This looks like a local machine issue rather than a code problem.

On 21 Dec 2017 02:49, "Arsh Singh" <notifications@github.com> wrote:

i can use 1.3 and tried same method on latest version but showing this
exception.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zhuowei/RaspberryJuice/issues/69#issuecomment-353243743>,
or mute the thread

**Comment by iosdev474** [comment]
I saw that some listeners are active on that port so i closed then and tried. It worked, Thanks 👍
