### ISSUE TITLE
Server creation issue

### ISSUE THREAD

**Issue by Gaurav-Reddy** [zhuowei/RaspberryJuice#72]
[01:01:03 INFO]: [RaspberryJuice] Opened connection to/127.0.0.1:61931.
[01:01:03 INFO]: [RaspberryJuice] Starting output thread!
[01:01:03 INFO]: [RaspberryJuice] Starting input thread
[01:01:33 WARN]: [RaspberryJuice] Task #2 for RaspberryJuice v1.9 generated an exception
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source) ~[?:1.8.0_151]
        at net.zhuoweizhang.raspberryjuice.RemoteSession.handleLine(RemoteSession.java:129) ~[?:?]
        at net.zhuoweizhang.raspberryjuice.RemoteSession.tick(RemoteSession.java:113) ~[?:?]
        at net.zhuoweizhang.raspberryjuice.RaspberryJuicePlugin$TickHandler.run(RaspberryJuicePlugin.java:167) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit.jar:git-Bukkit-cb61ac0]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [craftbukkit.jar:git-Bukkit-cb61ac0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:689) [craftbukkit.jar:git-Bukkit-cb61ac0]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit.jar:git-Bukkit-cb61ac0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit.jar:git-Bukkit-cb61ac0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit.jar:git-Bukkit-cb61ac0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[01:01:33 INFO]: [RaspberryJuice] Closed connection to/127.0.0.1:61931.

**Comment by martinohanlon** [comment]
Are you running Minecraft server v1.11 ? If so can you upgrade to v.1.12 and try again.

**Comment by martinohanlon** [comment]
Closing old issue, no reply
