### ISSUE TITLE
Error when running my script - how to I import the mcpi stuff into Python?

### ISSUE THREAD

**Issue by joshdragon04** [zhuowei/RaspberryJuice#73]
This happens when i run my script:
Traceback (most recent call last):
  File "C:\Documents and Settings\Joshua\Desktop\RaspberryJuice-master\src\main\resources\mcpi\api\python\original\mcpi\uhctest.py", line 1, in <module>
    import minecraft as minecraft
  File "C:\Documents and Settings\Joshua\Desktop\RaspberryJuice-master\src\main\resources\mcpi\api\python\original\mcpi\minecraft.py", line 1, in <module>
    from .connection import Connection
ValueError: Attempted relative import in non-package

**Comment by neuhaus** [comment]
You need to place your script outside of the mcpi folder

**Comment by martinohanlon** [comment]
Closing old issue, no reply.
