### ISSUE TITLE
Fails with modern Nukkit 1.0-SNAPSHOT. Any alternatives?

### ISSUE THREAD

**Issue by denisglotov** [zhuowei/RaspberryJuice#85]
Looks the plugin does not work with modern version of nukkit. Please advise, if fixing is worth the effort? Or are there good alternatives (for pocket editions)?

(I use https://github.com/PetteriM1/Pokkit to make bukkit plugins work with nukkit)
```
$ java -jar nukkit-1.0-SNAPSHOT.jar
...
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchFieldError: GOLD_SWORD
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[?:?]
        at nl.rutgerkok.pokkit.plugin.PokkitPluginLoader.loadPlugin(PokkitPluginLoader.java:113) ~[?:?]
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:272) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at nl.rutgerkok.pokkit.plugin.PokkitPluginManager.loadPlugins(PokkitPluginManager.java:202) ~[?:?]
        at org.bukkit.craftbukkit.v1_99_R9.CraftServer.loadPlugins(CraftServer.java:706) ~[?:?]
        at nl.rutgerkok.pokkit.pluginservice.PluginService.onLoad(PluginService.java:36) ~[?:?]
        at nl.rutgerkok.pokkit.Pokkit.lambda$onLoad$2(Pokkit.java:121) ~[?:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at nl.rutgerkok.pokkit.Pokkit.onLoad(Pokkit.java:121) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at nl.rutgerkok.pokkit.startup.NukkitHook.onLoad(NukkitHook.java:40) ~[?:?]
        at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:109) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:57) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:272) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:481) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) ~[nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NoSuchFieldError: GOLD_SWORD
        at net.zhuoweizhang.raspberryjuice.RaspberryJuicePlugin.<clinit>(RaspberryJuicePlugin.java:19) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[?:?]
        ... 24 more
```

**Comment by denisglotov** [comment]
It was due to outdated API version. Here's the fix https://github.com/zhuowei/RaspberryJuice/pull/86, please have a look.

**Comment by martinohanlon** [comment]
Closing.
